config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :addresses
  resources :friends
  get 'home/about'
  # root 'home#index'
  root 'friends#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends
  has_many :addresses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /addresses or /addresses.json
  def index
    # @addresses = Address.all
    @addresses = Address.where("user_id = #{current_user.id}")
  end

  # GET /addresses/1 or /addresses/1.json
  def show
    @addresses = Address.where("user_id = #{current_user.id}")
  end

  # GET /addresses/new
  def new
    # @address = Address.new
    @address = current_user.addresses.build
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses or /addresses.json
  def create
    # @address = Address.new(address_params)
    @address = current_user.addresses.build(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to address_url(@address), notice: "Address was successfully created." }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1 or /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to address_url(@address), notice: "Address was successfully updated." }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @address.destroy

    respond_to do |format|
      format.html { redirect_to addresses_url, notice: "Address was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @address = current_user.addresses.find_by(id: params[:id])
    redirect_to addresses_path, notice: "Not authorised to deal with that record" if @address.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def address_params
      params.require(:address).permit(:number, :street, :suburb, :city, :state, :postcode, :country, :user_id, :address_type)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    # @friends = Friend.all
    if user_signed_in?
      @friends = Friend.where("user_id = #{current_user.id}")
    end
  end

  # GET /friends/1 or /friends/1.json
  def show
    @friends = Friend.where("user_id = #{current_user.id}")
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not authorised to deal with that record" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
      # redirect_to friends_path, notice: "Not authorised to edit this user" if !@friend.id?
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_us = "HutchCoder is an international software services business."
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/addresses/_address.html.erb
<div id="<%= dom_id address %>">
  <p>
    <strong>Number:</strong>
    <%= address.number %>
  </p>

  <p>
    <strong>Street:</strong>
    <%= address.street %>
  </p>

  <p>
    <strong>Suburb:</strong>
    <%= address.suburb %>
  </p>

  <p>
    <strong>City:</strong>
    <%= address.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= address.state %>
  </p>

  <p>
    <strong>Postcode:</strong>
    <%= address.postcode %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= address.country %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= address.address_type %>
  </p>

</div>

app/views/addresses/_form.html.erb
<%= form_with(model: address) do |form| %>
  <% if address.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
        <% address.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :number, class:"form-control", placeholder:"Number" %>
  </div>

  <div>
    <%= form.text_field :street, class:"form-control", placeholder:"Street" %>
  </div>

  <div>
    <%= form.text_field :suburb, class:"form-control", placeholder:"Suburb" %>
  </div>

  <div>
    <%= form.text_field :city, class:"form-control", placeholder:"City" %>
  </div>

  <div>
    <%= form.text_field :state, class:"form-control", placeholder:"State" %>
  </div>

  <div>
    <%= form.text_field :postcode, class:"form-control", placeholder:"Postcode" %>
  </div>

  <div>
    <%= form.text_field :country, class:"form-control", placeholder:"Country" %>
  </div>

  <div>
    <%= form.text_field :address_type, class:"form-control", placeholder:"Type" %>
  </div>

  <div>
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render "form", address: @address %>

<br>

<div>
  <%= link_to "Show this address", @address, class:"btn btn-secondary" %> |
  <%= link_to "Delete this address", @address, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class:"btn btn-danger" %>
  <%= link_to "Back to addresses", addresses_path, class:"btn btn-secondary" %>
</div>

app/views/addresses/index.html.erb
<h1>Addresses</h1>

  <table class="table table-sm table-striped table-bordered table-hover">
    <thead id="address" class="container text-center thead-dark">
      <tr>
        <% @addresses.columns.each do |column| %>
          <th class="align-middle"><%= column.name.titleize %></th>
        <% end %>
     </tr>
    </thead>
    <tbody>
      <% @addresses.each do |address| %>
        <tr>
          <% address.attributes.each do |key, value| %>
            <% if key == 'id' %>
              <td class="align-middle"><%= link_to address.id, address %></td>
            <% else %>
              <td class="align-middle"><%=h value.to_s %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<%= link_to "New address", new_address_path, class:"btn btn-secondary" %>

app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render "form", address: @address %>

<br>

<div>
  <%= link_to "Back to addresses", addresses_path, class:"btn btn-secondary" %>
</div>

app/views/addresses/show.html.erb
<%= render @address %>

<div>
  <%= link_to "Edit this address", edit_address_path(@address), class:"btn btn-secondary" %> |
  <%= link_to "Delete this address", @address, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class:"btn btn-danger" %>
  <%= link_to "Back to addresses", addresses_path, class:"btn btn-secondary" %>

</div>

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%#= form.label :first_name, style: "display: block"%>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First name"  %>
  </div>

  <div class="form-group">
    <%#= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last name" %>
  </div>

  <div class="form-group">
    <%#= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="form-group">
    <%#= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %>
  </div>

  <div class="form-group">
    <%#= form.label :twitter, style: "display: block"%>
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter" %>
  </div>

  <div class="form-group">
    <%#= form.label :twitter, style: "display: block"%>
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>

  <div>
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <div class="jumbotron">
    <h1 class="display-4"><%= friend.first_name %> <%= friend.last_name %></h1>
    <p class="lead"><%= friend.email %></p>
    <hr class="my-4">
    <p>Ph: <%= friend.phone %></p>
    <p>Twitter: <%= friend.twitter %></p>
<!--    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>-->
  </div>
<!--  <p>-->
<!--    <strong>First name:</strong>-->
    <%#= friend.first_name %>
<!--  </p>-->

<!--  <p>-->
<!--    <strong>Last name:</strong>-->
    <%#= friend.last_name %>
<!--  </p>-->

<!--  <p>-->
<!--    <strong>Email:</strong>-->
    <%#= friend.email %>
<!--  </p>-->

<!--  <p>-->
<!--    <strong>Phone:</strong>-->
    <%#= friend.phone %>
<!--  </p>-->

<!--  <p>-->
<!--    <strong>Twitter:</strong>-->
    <%#= friend.twitter %>
<!--  </p>-->

</div>

app/views/friends/_showtable.html.erb
<div id="<%= dom_id friend %>">
  <tr>
    <td><%= friend.id %></td>
    <td><%= friend.first_name %></td>
    <td><%= friend.last_name %></td>
    <td><%= friend.email %></td>
    <td><%= friend.phone %></td>
    <td><%= friend.twitter %></td>
  </tr>
</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-secondary" %>
  <%= link_to "Delete this friend", @friend, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class:"btn btn-danger" %>
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>

  <h1>Friends</h1>
<thead id="friends">
  <table class="table table-sm table-striped table-bordered table-hover">
    <thead   class="container text-center thead-dark">
      <tr>
        <% @friends.columns.each do |column| %>
          <% if column.name == 'first_name' %>
            <th class="align-middle">Name</th>
          <% elsif column.name == 'last_name' %>
            <!--            do nothing-->
          <% else %>
            <th class="align-middle"><%= column.name.titleize %></th>
          <% end %>
        <% end %>
     </tr>
    </thead>
    <tbody>
      <% @friends.each do |friend| %>
        <tr>
          <% friend.attributes.each do |key, value| %>
            <% if key == 'first_name' %>
              <td class="align-middle"><%= link_to friend.first_name + ' ' + friend.last_name, friend %></td>
            <% elsif key == 'last_name' %>
<!--            do nothing-->
            <% else %>
              <td class="align-middle"><%=h value.to_s %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<%= link_to "New friend", new_friend_path, class:"btn btn-secondary" %>

<% else %>
  <%= render :partial => 'home/partial_index' %>
<% end %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
</div>

app/views/friends/show.html.erb
<%= render @friend %>

<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-success" %>
  <%= link_to "Delete this friend", @friend, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class:"btn btn-danger" %>
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Friend App', root_path, class:"navbar-brand" %>
<!--  <a class="navbar-brand" href="#">Friend App</a>-->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
<!--      <li class="nav-item active">-->
<!--        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
<!--      </li>-->
      <li class="nav-item">
        <%= link_to "About Us", home_about_path, class:"nav-link" %>
      </li>
      <% unless user_signed_in? %>
        <li class="nav-item align-middle">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item align-middle">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>
      <% else %>
        <li class="nav-item" align-middle>
          <%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete}, class:"nav-link" %>
        </li>
        <li class="nav-item align-middle">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add a Friend", new_friend_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Addresses", addresses_path, class:"nav-link" %>
        </li>
        <div class="navbar-brand align-middle" >
          <%= "Hello user " << current_user.id.to_formatted_s << " " << current_user.email %>
        </div>
      <% end %>
<!--      <li class="nav-item dropdown">-->
<!--        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">-->
<!--          Dropdown-->
<!--        </a>-->
<!--        <div class="dropdown-menu">-->
<!--          <a class="dropdown-item" href="#">Action</a>-->
<!--          <a class="dropdown-item" href="#">Another action</a>-->
<!--          <div class="dropdown-divider"></div>-->
<!--          <a class="dropdown-item" href="#">Something else here</a>-->
<!--        </div>-->
<!--      </li>-->
<!--      <li class="nav-item">-->
<!--        <a class="nav-link disabled">Disabled</a>-->
<!--      </li>-->
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/_partial_index.html.erb
<h1>Life goes on</h1>
<p>Welcome to our world</p>

app/views/home/about.html.erb
<h1>About us ...</h1>

<p>
  <%= @about_us %>
</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Ordered list</p>
<ol>
  <li>Item one</li>
  <li>Item two</li>
  <li>Item three</li>
</ol>

app/views/home/tabular.html.erb
<div id="friends">
  <table>
    <tr>
      <th>Id</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
    <% @friends.each do |friend| %>
      <%= render 'showtable' %>
    <% end %>
  </table>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

  <title>Friends App</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
<%= render 'home/header' %>
<div class="container">
  <br/>
  <% if notice  %>
    <%= render 'layouts/alerts' %>
  <% end %>
  <%= yield %>
</div>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
-->
</body>
</html>